---
# tasks file for ansible_filebeat

- name: get the rpm package facts
  package_facts:
    manager: "auto"

- name: uninstall old filebeat package
  yum:
    name: filebeat
    state: absent
  when: "ansible_facts.packages.filebeat[0].version != version"

- name: Install filebeat from elastic url
  yum:
    name: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ version }}-x86_64.rpm"
    state: present
  when: "ansible_facts.packages.filebeat[0].version != version"

- name: Filebeat configuration
  template:
    src: templates/filebeat.yml.jinja
    dest: "/etc/filebeat/filebeat.yml"
    mode: 0644
  when: "ansible_facts.packages.filebeat[0].version != version"

- name: Filebeat service enabled - systemd lovers
  systemd:
    name: filebeat
    enabled: yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version > '6' and "ansible_facts.packages.filebeat[0].version != version"

- name: Filebeat service enabled - initid lovers
  service:
    name: filebeat
    enabled: yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version < '7' and "ansible_facts.packages.filebeat[0].version != version"
